[CLEAN_TESTS] Patch to clean tests and add comments
The generated files, now have a small disclaimer at the
top of the file, informing about the fact that the files
have been generated. This is just a reminder so programmers
do not modify the files without being informed that this
might be dangerous.

It is assumed that git or gerrit is used by most developers
so these type of errors should be noticed or easily fixed.

In the generated test cases unneeded repetition of the gtest
include-files were removed.

Also the sha1sum of the file is now calculated and inserted
into the generated code. This way a Makefile could check
with a simple grep-sed-statement if the code is up-to-date.

diff --git a/scripts/gen.sh.in b/scripts/gen.sh.in
--- a/scripts/gen.sh.in
+++ b/scripts/gen.sh.in
@@ -85,6 +85,13 @@ if [ "$?" != "0" ] ; then
     exit 1
 fi
 
+sha1sum $filename > $filename.sha1
+if [ "$?" != "0" ] ; then
+    echo "${PACKAGE_NAME_VERSION}:ERROR - sha1sum was unable to generate the .sha1 file for $file_name!" | tee -a "$filename.log"
+    exit 1
+fi
+
+
 gsl -script:$PACKAGE_PREFIX_DIR/cast_xml_generate_printers-$PACKAGE_VERSION.gsl -cstandard:$cstandard -type:Enumeration,Struct,Class -file:$file_name $filename.xml >> "$filename.log"
 if [ "$?" != "0" ] ; then
     echo "${PACKAGE_NAME_VERSION}:ERROR - gsl was unable to generate the code from the xml-representation!" | tee -a "$filename.log"
